### ISSUE TITLE
Fix hydration issue

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/website#100]
- in every page inside dashboard, there is hydration issue coming on refresh :weird:

**Comment by harshjohar** [comment]
Found the issue, issue is caused by the components using the `parseCookies` method of `nookies` package. There are two way out of this:
- implementing `next-auth` as mentioned in #95 
- using `universal-cookies` package

By reading docs and analysing the use case, we are going ahead with `next-auth`
